// Code generated by Wire protocol buffer compiler, do not edit.
// Source: redacted.
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.squareup.protos.common.validation

import kotlin.Boolean
import kotlin.Suppress
import kotlin.`annotation`.AnnotationRetention
import kotlin.`annotation`.AnnotationTarget
import kotlin.`annotation`.Retention
import kotlin.`annotation`.Target

/**
 * Indicates that the field must be present and not empty.  Applies to strings and byte strings
 */
@Retention(AnnotationRetention.RUNTIME)
@Target(
  AnnotationTarget.PROPERTY,
  AnnotationTarget.FIELD,
)
public annotation class NotEmptyOption(
  public val `value`: Boolean,
)
