// Code generated by Wire protocol buffer compiler, do not edit.
// Source: redacted.
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.squareup.protos.sawmill

import com.squareup.protos.common.validation.NotEmptyOption
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class EventstreamV2Event(
  @NotEmptyOption(true)
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 0,
  )
  public val uuid: String? = null,
  @NotEmptyOption(true)
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val catalog_name: String? = null,
  @NotEmptyOption(true)
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val app_name: String? = null,
  /**
   * MICROSECONDS since Unix epoch.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    schemaIndex = 3,
  )
  public val recorded_at_usec: Long? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 4,
  )
  public val json_data: String? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 5,
  )
  public val secret_token: String? = null,
  /**
   * redacted.
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 6,
  )
  public val es2_debug_trace_id: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<EventstreamV2Event, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is EventstreamV2Event) return false
    if (unknownFields != other.unknownFields) return false
    if (uuid != other.uuid) return false
    if (catalog_name != other.catalog_name) return false
    if (app_name != other.app_name) return false
    if (recorded_at_usec != other.recorded_at_usec) return false
    if (json_data != other.json_data) return false
    if (secret_token != other.secret_token) return false
    if (es2_debug_trace_id != other.es2_debug_trace_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (uuid?.hashCode() ?: 0)
      result = result * 37 + (catalog_name?.hashCode() ?: 0)
      result = result * 37 + (app_name?.hashCode() ?: 0)
      result = result * 37 + (recorded_at_usec?.hashCode() ?: 0)
      result = result * 37 + (json_data?.hashCode() ?: 0)
      result = result * 37 + (secret_token?.hashCode() ?: 0)
      result = result * 37 + (es2_debug_trace_id?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (uuid != null) result += """uuid=${sanitize(uuid)}"""
    if (catalog_name != null) result += """catalog_name=${sanitize(catalog_name)}"""
    if (app_name != null) result += """app_name=${sanitize(app_name)}"""
    if (recorded_at_usec != null) result += """recorded_at_usec=$recorded_at_usec"""
    if (json_data != null) result += """json_data=${sanitize(json_data)}"""
    if (secret_token != null) result += """secret_token=${sanitize(secret_token)}"""
    if (es2_debug_trace_id != null) result += """es2_debug_trace_id=${sanitize(es2_debug_trace_id)}"""
    return result.joinToString(prefix = "EventstreamV2Event{", separator = ", ", postfix = "}")
  }

  public fun copy(
    uuid: String? = this.uuid,
    catalog_name: String? = this.catalog_name,
    app_name: String? = this.app_name,
    recorded_at_usec: Long? = this.recorded_at_usec,
    json_data: String? = this.json_data,
    secret_token: String? = this.secret_token,
    es2_debug_trace_id: String? = this.es2_debug_trace_id,
    unknownFields: ByteString = this.unknownFields,
  ): EventstreamV2Event = EventstreamV2Event(uuid, catalog_name, app_name, recorded_at_usec, json_data, secret_token, es2_debug_trace_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<EventstreamV2Event> =
        object : ProtoAdapter<EventstreamV2Event>(
      FieldEncoding.LENGTH_DELIMITED, 
      EventstreamV2Event::class, 
      "type.googleapis.com/squareup.sawmill.EventstreamV2Event", 
      PROTO_2, 
      null, 
      "squareup/sawmill/service.proto"
    ) {
      override fun encodedSize(`value`: EventstreamV2Event): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.uuid)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.catalog_name)
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.app_name)
        size += ProtoAdapter.INT64.encodedSizeWithTag(4, value.recorded_at_usec)
        size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.json_data)
        size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.secret_token)
        size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.es2_debug_trace_id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: EventstreamV2Event) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uuid)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.catalog_name)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.app_name)
        ProtoAdapter.INT64.encodeWithTag(writer, 4, value.recorded_at_usec)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.json_data)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.secret_token)
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.es2_debug_trace_id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: EventstreamV2Event) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.es2_debug_trace_id)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.secret_token)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.json_data)
        ProtoAdapter.INT64.encodeWithTag(writer, 4, value.recorded_at_usec)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.app_name)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.catalog_name)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uuid)
      }

      override fun decode(reader: ProtoReader): EventstreamV2Event {
        var uuid: String? = null
        var catalog_name: String? = null
        var app_name: String? = null
        var recorded_at_usec: Long? = null
        var json_data: String? = null
        var secret_token: String? = null
        var es2_debug_trace_id: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> uuid = ProtoAdapter.STRING.decode(reader)
            2 -> catalog_name = ProtoAdapter.STRING.decode(reader)
            3 -> app_name = ProtoAdapter.STRING.decode(reader)
            4 -> recorded_at_usec = ProtoAdapter.INT64.decode(reader)
            5 -> json_data = ProtoAdapter.STRING.decode(reader)
            6 -> secret_token = ProtoAdapter.STRING.decode(reader)
            7 -> es2_debug_trace_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return EventstreamV2Event(
          uuid = uuid,
          catalog_name = catalog_name,
          app_name = app_name,
          recorded_at_usec = recorded_at_usec,
          json_data = json_data,
          secret_token = secret_token,
          es2_debug_trace_id = es2_debug_trace_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: EventstreamV2Event): EventstreamV2Event = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
