name: publish

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

permissions:
  contents: read

jobs:
  publish:
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SECRET_PASSPHRASE }}
    runs-on: ubuntu-latest
    if: github.repository == 'block/ide-metrics-plugin' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check non-IDE plugin
        run: './gradlew check -x :check -s'

      - name: Check IDE plugin
        run: './gradlew :check -s'

      - name: Dependency Analysis
        run: './gradlew :buildHealth -s'

      # TODO(tsr): Need to adjust this step with proper publishing tasks.
      - name: Publish artifacts
        run: './gradlew publishAllPublicationsToMavenCentralRepository -s --no-configuration-cache'
